local options = {
  termguicolors = true,                                                               -- set term gui colors (most terminals support this)
  backup = false,                                                                     -- creates a backup file
  clipboard = 'unnamedplus',                                                          -- allows neovim to access the system clipboard
  cmdheight = 1,                                                                      -- more space in the neovim command line for displaying messages
  completeopt = { 'menuone', 'noselect' },                                            -- mostly just for cmp
  conceallevel = 0,                                                                   -- so that `` is visible in markdown files
  fileencoding = 'utf-8',                                                             -- the encodinkg written to a file
  hlsearch = true,                                                                    -- highlight all matches on previous search pattern
  ignorecase = true,                                                                  -- ignore case in search patterns
  mouse = 'a',                                                                        -- allow the mouse to be used in neovim
  pumheight = 10,                                                                     -- pop up menu height
  showmode = false,                                                                   -- we don't need to see things like -- INSERT -- anymore
  showtabline = 0,                                                                    -- always show tabs
  smartcase = true,                                                                   -- smart case
  smartindent = true,                                                                 -- make indenting smarter again
  splitbelow = true,                                                                  -- force all horizontal splits to go below current window
  splitright = true,                                                                  -- force all vertical splits to go to the right of current window
  swapfile = false,                                                                   -- creates a swapfile
  timeoutlen = 200,                                                                   -- time to wait for a mapped sequence to complete (in milliseconds)
  updatetime = 50,                                                                    -- faster completion (4000ms default)
  writebackup = false,                                                                -- do not edit backups
  expandtab = true,                                                                   -- convert tabs to spaces
  shiftwidth = 2,                                                                     -- the number of spaces inserted for each indentation
  tabstop = 4,                                                                        -- insert 2 spaces for a tab
  cursorline = true,                                                                  -- highlight the current line
  laststatus = 3,                                                                     --
  showcmd = false,                                                                    --
  number = true,                                                                      -- set numbered lines
  relativenumber = true,                                                              -- set relative numbered lines
  numberwidth = 4,                                                                    -- set number column width to 2 {default 4}
  signcolumn = 'yes',                                                                 -- always show the sign column, otherwise it would shift the text each time
  wrap = false,                                                                       -- display lines as one long line
  linebreak = true,                                                                   -- companion to wrap, don't split words
  scrolloff = 10,                                                                     -- is one of my fav
  sidescrolloff = 10,
  listchars = { trail = '', tab = '', nbsp = '_', extends = '>', precedes = '<' }, -- highlight
  list = true,
  wildmenu = true,                                                                    -- wildmenu
  sessionoptions = 'blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal',
  autoindent = true,
  guicursor = 'n-v-ve-c:block100-blinkon0-Cursor,i-ci:ver100-blinkon0-Cursor2',
  shell = 'fish',
  inccommand = 'split',
  smarttab = true,
  breakindent = true,
  ai = true,
  si = true,
  backspace = 'indent,eol,start',
  --undodir = os.getenv('HOME') .. '/.vim/undodir',
  --undofile = true, -- enable persistent undo
}
for key, value in pairs(options) do
  vim.opt[key] = value
end
